missan_Pro/missan_Pro/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import include
from missan_app.missan_views import user_views


app_name = "missan_app"

urlpatterns = [
    path('',user_views.user_login,name='user_login'),
    path('admin/', admin.site.urls),
    re_path('',include('missan_app.urls')),
]

missan_Pro/missan_app/urls.py
from django.urls import path,re_path
from missan_app.missan_views import user_views
from missan_app.missan_views import driver_views
from missan_app import views
from django.conf.urls import include

app_name = 'missan_app'

urlpatterns = [
        path('home',views.home,name='home'),
        path('driversersearch',driver_views.driver_search,name='driversersearch'),
        path('adddriver',driver_views.add_driver,name='add_driver'),
        path('user_login',user_views.user_login,'user_login'),
        path('adduser',user_views.register,name='register'),
        path('login',user_views.user_login,name='user_login'),
        path('logout',user_views.user_logout,name='logout'),
        re_path(r'$',user_views.user_login,name='user_login'),
]

missan_Pro/missan_app/models.py
from django.db import models
from missan_app.missan_models import users_models
from missan_app.missan_models import driver_models

missan_Pro/missan_app/views.py
from django.shortcuts import render
from missan_app.missan_views import user_views
from missan_app.missan_views import driver_views
from missan_app.missan_views.driver_views import add_driver


def home(request):

    if request.user.is_authenticated:
        return render(request,'missan_app/home.html')
    else:
        return render(request,'missan_app/login.html')

missan_Pro/templates/missan_app/adddriver.html
<!DOCTYPE html>
        {% extends 'missan_app/base.html' %}
        {% load static %}
        {% block body_block %}
                      <br>
                      <div class="container" align="right">
                        {% if driver_form.errors %}
                            <ul>
                            {% for field in driver_form %}
                                  {% for error in field.errors %}
                                        <!-- <div class="alert alert-danger"> -->
                                            <div style="color:red;"><li>{{ error|escape}}</li></div>
                                        <!-- </div> -->
                                  {% endfor %}
                            </ul>
                            {% endfor %}
                            {% for error in driver_form.non_field_errors %}
                                    <!-- <div class="alert alert-danger"> -->
                                        <div color="red">{{ error|escape }} </div>
                                    <!-- </div> -->
                            {% endfor %}
                        {% endif %}
                        {% if expiry_date_iqama_driver_license %}
                        <ul>
                        <div style="color:red;"><li>{{ expiry_date_iqama_driver_license }}</li></div>
                        </ul>
                        {% endif %}
                      </div>

            <br>
              <div class="container">
                <div class="jumbotron">
                  <form action="{% url 'missan_app:add_driver' %}" method="post">
                    {% csrf_token %}
                            <div class="input-group">
                                <label for="">الإسم :</label>
                                <input type="text" name="first_name" class="form-control" required>
                                <input type="text" name="second_name" class="form-control">
                                <input type="text" name="fourth_name" class="form-control">
                                <input type="text" name="last_name" class="form-control" required>
                              </div>
                              <br>
                              <div class="input-group">

                                  <label for="iqama_number">رقم الإقامة: </label>
                                  <input type="text" name="iqama_number"  class="form-control" required maxlength="10">
                                  <label for="iqama_expiry_date">تاريخ إنتهاء الإقامة :</label>
                                  <input type="date" name="iqama_expiry_date" class="form-control" required>
                                  <label for="driver_license_expiry_date">تاريخ إنتهاء الرخصة :</label>
                                  <input type="date" name="driver_license_expiry_date" class="form-control" required>
                                </div>
                                <br>
                                <div class="input-group">
                                    <label for="sponsor_name">اسم الكفيل :</label>
                                    <input type="text" name="sponsor_name" class="form-control" required>
                                    <label for="joining_date">تاريخ مباشرة العمل :</label>
                                    <input type="date" name="joining_date" class="form-control" required>
                                    <label for="city">المدينة :</label>
                                    <input type="text" name="city" class="form-control" required>
                                  </div>
                                  <br>
                                  <div class="input-group">
                                      <label for="area">الحي :</label>
                                      <input type="text" name="area" class="form-control" required>
                                      <label for="street">اسم الشارع :</label>
                                      <input type="text" name="street" class="form-control" required>
                                    </div>
                                    <br>
                                    <div class="input-group">
                                        <label for="car_type">نوع السيارة :</label>
                                        <input type="text" name="car_type" class="form-control" required>
                                        <label for="car_plate_number">رقم اللوحة :</label>
                                        <input type="text" name="car_plate_number" class="form-control" required>
                                        <label for="car_color">لون السيارة :</label>
                                        <input type="text" name="car_color" class="form-control" required>
                                        <label for="car_model">سنة الصنع</label>
                                        <input type="text" name="car_model" class="form-control" required maxlength="4">
                                      </div>
                                      <br>
                                    <div class="input-group">
                                      <label for="current_application">التطبيق الحالي :</label>
                                      <input type="text" name="current_application" class="form-control">
                                      <label for="previous_application">التطبيق السابق :</label>
                                      <input type="text" name="previous_application" class="form-control">
                                      <label for="knows_aout_us">كيف عرفتنا</label>
                                      <input type="text" name="knows_aout_us" class="form-control">
                                    </div>
                                    <br>
                                    <button  type="submit" class="btn  btn-primary btn-lg btn-block" >إضافة</button>
                  </form>
                </div>
              </div>
        {% endblock %}

missan_Pro/templates/missan_app/adddriverOld.html
<!DOCTYPE html>
{% extends 'missan_app/base.html' %}
{% load static %}
{% block body_block %}
<div class="container">
<div class="jumbotron">

    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      <div class="form-group">
      {{ add_driver }}
    </div>
      <input type="submit" name="" value="Insert">
    </form>
    </form>

</div>
</div>
  {% endblock %}

missan_Pro/templates/missan_app/adduser.html
<!DOCTYPE html>
{% extends 'missan_app/base.html' %}
{% load static %}
{% block body_block %}
<div class="container">
<div class="jumbotron">
  {% if registered %}
      <h1>Thank you for registeration !!</h1>
  {% else %}
    <h1>Register Here</h1>
    <h3>Fill out the form</h3>
    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ user_form.as_table }}
      <input type="submit" name="" value="Register">
    </form>
    {% endif %}
    </form>

</div>
</div>
  {% endblock %}

missan_Pro/templates/missan_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ar" dir="rtl">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static "bootstrap-4.3.1-dist/css/bootstrap.min.css" %}">
    <script src="{% static "jquery-3.4.1.js" %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-nav navbar-expand-sm navbar-dark bg-primary">
        <img src="{% static "images/MissanLogo.png" %}"  width="150" height="50" alt="">
        <div align="right">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              جاهـــز
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'missan_app:add_driver' %}">إضافة سائق جديد</a>
                <a class="dropdown-item" href="{% url 'missan_app:driversersearch' %}">بحث عن سائق</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'missan_app:register' %}">إنشاء مستخدم جديد</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="">التقارير</a>
            </li>

            <li><a class="nav-link" href="{% url 'missan_app:logout' %}">تسجيل خروج</a></li>

          </ul>
        </div>
        </div>
    </nav>
    {% block body_block %}
      <!-- anything out of this will be inherited if you extend -->
    <h1>Base Page</h1>
    {% endblock %}

<script src="{% static "bootstrap-4.3.1-dist/js/bootstrap.min.js" %}"></script>
  </body>
</html>

missan_Pro/templates/missan_app/driversearch.html
<!DOCTYPE html>
        {% extends 'missan_app/base.html' %}
        {% load static %}
        {% block body_block %}
        <br>
        <div class="container">
          <form>
            <div class="row">
              <div class="input-group">
              <!-- <div class="col"> -->
                <input type="text" name="iqama_number" class="form-control" placeholder="رقم الاقامة">
              <!-- </div> -->
              <!-- <div class="col"> -->
                <input type="text" name="first_name" class="form-control" placeholder="الاسم الاول">
              <!-- </div> -->
              <!-- <div class="col"> -->
                <input type="text" name="last_name" class="form-control" placeholder="الاسم الاخير">
              <!-- </div> -->
              <!-- <div class="col"> -->
                <button  type="submit" class="btn  btn-primary btn-sm" >بحث</button>
              <!-- </div> -->
            </div>
            </div>
          </form>
        </div>
        <br>
            <div class="container">
              <div class="jumbotron">
                <form action="{% url 'missan_app:add_driver' %}" method="post">


                </form>
              </div>
            </div>
        {% endblock %}

missan_Pro/templates/missan_app/home.html
<!DOCTYPE html>
{% extends 'missan_app/base.html' %}
{% load static %}
{% block body_block %}
  <h1>Home Page</h1>
  {% endblock %}

missan_Pro/templates/missan_app/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ar" dir="rtl">
  <head>
    <meta charset="utf-8">
    <title>تسجيل الدخول إلى نظام ميسان</title>
    <link rel="stylesheet" href="{% static "bootstrap-4.3.1-dist/css/bootstrap.min.css" %}">
  </head>
  <body>
        <br>
          <div class="container">
          <div class="row">
          <img src="{% static "images/MissanLogo.png" %}" class="img-fluid" alt="Responsive image"  height="100" width="300"></td>
          </div>
          </div>
        <br>

      <div align="right">
      <div class="container">
      <div class="jumbotron">
                <form action="{% url 'missan_app:user_login' %}" method="post">
                  {% csrf_token %}
                    <div class="form-group">
                      <h4><label for="exampleInputEmail1" style="font-family:areal;">اسم المستخدم</label></h4>
                      <input type="text" class="form-control" id="exampleInputEmail1" name="username">
                      <small id="emailHelp" class="form-text text-muted">في حدوث اي مشكلة يرجى الاتصال بمدير النظام وشكراً ..</small>
                    </div>
                    <div class="form-group">
                    <h4>  <label for="exampleInputPassword1" style="font-family:areal;">الرقم السري</label></h4>
                      <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                    </div>
                    <button type="submit" class="btn btn-primary">دخول</button>
                </form>
        </div>
        </div>
        </div>
  </body>
</html>